<a href="https://colab.research.google.com/github/vijayshankarrealdeal/intro_to_pytorch/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch as th

In [2]:
tensor =  th.Tensor([
                     [[1,2],[3,4]],
                     [[5, 6], [7, 8]], 
                      [[9, 0], [1, 2]]
])
tensor

tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]],

        [[9., 0.],
         [1., 2.]]])

In [3]:
#use cpu and gpu

In [4]:
tensor.device

device(type='cpu')

In [5]:
new_tensor = tensor.to('cuda')

In [6]:
new_tensor.device

device(type='cuda', index=0)

In [7]:
th.ones_like(new_tensor)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]], device='cuda:0')

In [8]:
th.zeros_like(new_tensor)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]], device='cuda:0')

In [9]:
th.randn_like(new_tensor)

tensor([[[-0.3725,  0.3783],
         [-1.9592, -0.2917]],

        [[-0.7391, -0.5091],
         [-0.4836,  0.9513]],

        [[ 0.4105, -1.1117],
         [-1.0380, -0.1901]]], device='cuda:0')

In [10]:
var = th.randn(13,1,device='cuda')

In [11]:
var.mean()

tensor(-0.4872, device='cuda:0')

In [12]:
var.std()

tensor(0.9655, device='cuda:0')

In [13]:
#PyTorch Neural Network Module 

In [14]:
import torch.nn as nn

In [15]:
linear = nn.Linear(10,2)
input = th.randn(3,10)
output =linear(input)
output

tensor([[ 0.0612, -0.0267],
        [-0.5639, -0.2018],
        [-0.3166,  0.6121]], grad_fn=<AddmmBackward>)

In [16]:
relu = nn.ReLU()
outpu = relu(output)

In [17]:
batch_norm = nn.BatchNorm1d(2)
outp = batch_norm(outpu) 
outp

tensor([[ 1.4058, -0.7071],
        [-0.7029, -0.7071],
        [-0.7029,  1.4141]], grad_fn=<NativeBatchNormBackward>)

In [18]:
mul_lay = nn.Sequential(
    nn.Linear(5,2),
    nn.BatchNorm1d(2),
    nn.ReLU()
)
tensor_t = th.randn(5,5) + 1
mul_lay(tensor_t)

tensor([[1.5149, 1.3147],
        [0.3346, 0.1820],
        [0.0000, 0.0000],
        [0.0000, 0.6235],
        [0.3593, 0.0000]], grad_fn=<ReluBackward0>)

In [19]:
import torch.optim as optims

In [20]:
adm_optims = optims.Adam(mul_lay.parameters(),lr = 1e-1)
adm_optims

Adam (
Parameter Group 0
    amsgrad: False
    betas: (0.9, 0.999)
    eps: 1e-08
    lr: 0.1
    weight_decay: 0
)

In [21]:
train_example = th.randn(100,5) + 1
adm_optims.zero_grad()

In [22]:
cur_loss = th.abs(1 - mul_lay(train_example)).mean()

In [23]:
cur_loss.backward()
adm_optims.step()
print(cur_loss)

tensor(0.7597, grad_fn=<MeanBackward0>)
